root = "."
tmp_dir = "tmp"
[build]
cmd = "go build -o ./tmp/main -buildvcs=false ."
bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", "tmp", "vendor"]
exclude_file = []
delay = 200
kill_signal = "SIGTERM"
kill_timeout = 1000

[log]
level = "debug"
[log.colors]
main = "yellow"
watcher = "cyan"
building = "magenta"
