# Config file for air

# Working directory
root = "/app"

# Main package
cmd = "./main.go"

# Binary file output
bin = "main"

# Watch these directories and files for changes
[build]
watch_dirs = ["./"]
include_ext = ["go", "tpl", "tmpl", "html"]

# Exclude these files or directories from being watched
[build.exclude]
dirs = ["vendor", "node_modules", "dist"]
files = [".air.toml"]

# Command to build
build_cmd = "go build -o ./main ."

# Command to run binary
run_cmd = "./main"
