[build]
cmd = "go build -o ./bin/server ./cmd/server"
bin = "./bin/server"
full_bin = "APP_ENV=development ./bin/server"
log = "air.log"

[dirs]
includes = ["."]
excludes = ["vendor", "bin", ".git", "node_modules"]
