version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - GO_ENV=development
    volumes:
      - ./app:/engbot/app
      - ./resources:/engbot/resources
