# Config file for air

# Working directory
root = "."

# Main package
cmd = "main.go"

# Binary file output
bin = "main"

# Watch these directories and files for changes
[build]
watch_dirs = ["."]
include_ext = ["go", "tpl", "tmpl", "html"]

# Exclude these files or directories from being watched
[build.exclude]
dirs = ["vendor"]
files = ["air.toml"]
